{
 "title": "Workload resources",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "Cluster", "query": { "query": "label_values(clusterName)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{clusterName=~\"$cluster_name\", phase=\"Active\"},namespace)"
    }
   },
   {
    "name": "kind",
    "label": "Kind",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", workload=~\".+\"}, workload_type)"
    }
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", workload=~\".+\", workload_type=~\"$kind\"},workload)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods Failed Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (pod)(kube_pod_status_phase{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", phase=\"Failed\"}) * on(pod) group_left(created_by_name) kube_pod_info{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", created_by_name=~\"$workload\", created_by_kind=~\"(?i:($kind))\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "changes(kube_pod_container_status_restarts_total{clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}[$__rate_interval]) * on (pod)\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$kind\"}",
     "legendFormat": "Restarts {{pod}}"
    },
    {
     "legendFormat": "OOMKilled and CrashLoopBackOff {{workload}}"
    }
   ]
  },
  {
   "title": "Pod restarts by workload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}[$__rate_interval]) * on (pod)\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$kind\"}) by (workload)",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Pod killed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "(kube_pod_container_status_last_terminated_reason{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", reason=~\"OOMKilled\"}  * on (pod)\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$kind\"})",
     "legendFormat": "OOMKilled {{pod}}"
    },
    {
     "expr": "(kube_pod_container_status_last_terminated_reason{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", reason=~\"CrashLoopBackOff\"}  * on (pod)\ngroup_left(workload) namespace_workload_pod:kube_pod_owner:relabel{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$kind\"})",
     "legendFormat": "CrashLoopBackOff {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", workload_type=~\"$kind\", workload=~\"$workload\"}\n) by (workload, workload_type)\n",
     "legendFormat": "{{workload}} - {{workload_type}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", clusterName=~\"$cluster_name\", namespace=~\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", workload_type=~\"$kind\", workload=~\"$workload\"}\n) by (workload, workload_type)\n",
     "legendFormat": "{{workload}} - {{workload_type}}"
    }
   ]
  },
  {
   "title": "Receive traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$kind\"}) by (workload))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Transmit traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$kind\"}) by (workload))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Received packets dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$kind\"}) by (workload))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Received packets dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", clusterName=~\"$cluster_name\", namespace=~\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{clusterName=~\"$cluster_name\", namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$kind\"}) by (workload))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  }
 ]
}