apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-system
spec:
  mode: daemonset
  image: otel/opentelemetry-collector-contrib:0.92.0
  serviceAccount: attributes-account
  env:
    - name: KUBE_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

      # Dummy receiver that's never used, because a pipeline is required to have one.
      otlp/spanmetrics:
        protocols:
          grpc:
            endpoint: "localhost:65535"
    processors:
      batch:
      resourcedetection:
        detectors: [env, system]
        timeout: 2s
        override: false
      spanmetrics:
        metrics_exporter: prometheus
      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        filter:
          node_from_env_var: KUBE_NODE_NAME
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
      logging:
      otlp:
        endpoint: "jaeger-tracing-collector.tracing-system.svc:4317"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [resourcedetection, k8sattributes, spanmetrics, batch]
          exporters: [otlp,logging]    
        metrics/spanmetrics:
          receivers: [otlp/spanmetrics]
          exporters: [prometheus]