kind: Grafana
apiVersion: grafana.integreatly.org/v1beta1
metadata:
  name: grafana
  labels:
    dashboards: grafana
spec:
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: <storageClass-name> # set your own storage class
      volumeMode: Filesystem
  config:
    log:
      mode: console
      level: warn
    server:
      domain: monitoring.observability.[yourdomain].com
      protocol: http
      https_port: "443"
      root_url: "https://%(domain)s/"
    auth:
      disable_login_form: "false"
    security:
      admin_user: root
      admin_password: secret

