# an example envoy-v3 configuration.
apiVersion: v1
kind: Service
metadata:
  name: thanos-envoy-sidecar
  labels:
    name: thanos-envoy-sidecar
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: query
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: thanos
  ports:
    - name: envoy-observee01
      protocol: TCP
      port: 10000
      targetPort: 10000
  sessionAffinity: "None"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-envoy-config
data:
  envoy.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address: { address: 0.0.0.0, port_value: 9901 }
    static_resources:
      listeners:
      - name: envoy-observee01
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 10000
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: AUTO
              access_log:
              - name: envoy.access_loggers.file
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                  path: /dev/stdout
                  log_format:
                    text_format: |
                      [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%"
                      %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION%
                      %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%"
                      "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" "%UPSTREAM_TRANSPORT_FAILURE_REASON%"\n   
              - name: envoy.access_loggers.file
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                  path: /dev/stdout
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route: 
                      cluster: envoy-observee01
                      host_rewrite_literal: prometheus-envoy-observee01.observability.[yourdomain].com
              http_filters:
              - name: envoy.filters.http.router
      clusters:
      - name: envoy-observee01
        connect_timeout: 30s
        type: LOGICAL_DNS
        http2_protocol_options: {}
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: envoy-observee01
          endpoints:
            - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: prometheus-envoy-observee01.observability.[yourdomain].com
                      port_value: 443
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            common_tls_context:
              alpn_protocols:
              - h2
              - http/1.1
            sni: prometheus-envoy-observee01.observability.[yourdomain].com