{
 "title": "Alertmanager",
 "description": "Check the status of Alertmanager for each cluster.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "integration",
    "label": "Integration",
    "query": {
     "query": "label_values(alertmanager_notifications_total{integration=~\".*\"}, integration)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(alertmanager_alerts, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(alertmanager_alerts, service)"
    }
   },
   { "name": "cluster_name", "label": "Cluster", "query": { "query": "label_values(clusterName)" } }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(alertmanager_alerts{clusterName=~\"$cluster_name\", namespace=~\"$namespace\",service=~\"$service\"}) by (clusterName)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts receive rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(alertmanager_alerts_received_total{namespace=~\"$namespace\",service=~\"$service\"}[$__rate_interval])) by (clusterName)",
     "legendFormat": "Received {{clusterName}}"
    },
    {
     "expr": "sum(rate(alertmanager_alerts_invalid_total{namespace=~\"$namespace\",service=~\"$service\"}[$__rate_interval])) by (clusterName)",
     "legendFormat": "Invalid {{clusterName}}"
    }
   ]
  },
  { "title": "Notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$integration: Notifications Send Rate",
   "type": "timeseries",
   "description": "rate of successful and invalid notifications sent by the Alertmanager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(alertmanager_notifications_total{namespace=~\"$namespace\",service=~\"$service\", integration=\"$integration\", clusterName=~\"$cluster_name\"}[$__rate_interval])) by (integration,clusterName)",
     "legendFormat": "{{clusterName}} total"
    },
    {
     "expr": "sum(rate(alertmanager_notifications_failed_total{namespace=~\"$namespace\",service=~\"$service\", integration=\"$integration\", clusterName=~\"$cluster_name\"}[$__rate_interval])) by (integration,clusterName)",
     "legendFormat": "{{clusterName}} failed"
    }
   ]
  },
  {
   "title": "$integration: Notification Duration",
   "type": "timeseries",
   "description": "latency of notifications sent by the Alertmanager",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum(rate(alertmanager_notification_latency_seconds_bucket{namespace=~\"$namespace\",service=~\"$service\", integration=\"$integration\", clusterName=~\"$cluster_name\"}[$__rate_interval])) by (le,clusterName)\n) \n",
     "legendFormat": "{{clusterName}} 99th percentile"
    },
    {
     "expr": "histogram_quantile(0.50,\n  sum(rate(alertmanager_notification_latency_seconds_bucket{namespace=~\"$namespace\",service=~\"$service\", integration=\"$integration\", clusterName=~\"$cluster_name\"}[$__rate_interval])) by (le,clusterName)\n) \n",
     "legendFormat": "{{clusterName}} mean"
    },
    {
     "expr": "sum(rate(alertmanager_notification_latency_seconds_sum{namespace=~\"$namespace\",service=~\"$service\", integration=\"$integration\", clusterName=~\"$cluster_name\"}[$__rate_interval])) by (clusterName)\n/\nsum(rate(alertmanager_notification_latency_seconds_count{namespace=~\"$namespace\",service=~\"$service\", integration=\"$integration\", clusterName=~\"$cluster_name\"}[$__rate_interval])) by (clusterName)\n",
     "legendFormat": "{{clusterName}} average"
    }
   ]
  },
  { "title": "Alert Lists", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Normal",
   "type": "alertlist",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 20 },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pending",
   "type": "alertlist",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 20 },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Firing",
   "type": "alertlist",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 20 },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  }
 ]
}