{
 "title": "Jaeger",
 "tags": [ "tracing" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "Cluster", "query": { "query": "label_values(clusterName)" } },
   {
    "name": "collector_build_version",
    "query": {
     "query": "label_values(jaeger_collector_build_info{clusterName=~\"$cluster_name\"}, version)"
    }
   },
   {
    "name": "collector_build_date",
    "query": {
     "query": "label_values(jaeger_collector_build_info{clusterName=~\"$cluster_name\"}, build_date)"
    }
   },
   {
    "name": "collector_build_revision",
    "query": {
     "query": "label_values(jaeger_collector_build_info{clusterName=~\"$cluster_name\"}, revision)"
    }
   },
   {
    "name": "query_build_version",
    "query": {
     "query": "label_values(jaeger_query_build_info{clusterName=~\"$cluster_name\"}, version)"
    }
   },
   {
    "name": "query_build_date",
    "query": {
     "query": "label_values(jaeger_query_build_info{clusterName=~\"$cluster_name\"}, build_date)"
    }
   },
   {
    "name": "query_build_revision",
    "query": {
     "query": "label_values(jaeger_query_build_info{clusterName=~\"$cluster_name\"}, revision)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Build Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "### Collector\n\nversion: ${collector_build_version}\n\nrevision: ${collector_build_revision}\n\nbuild date: ${collector_build_date}"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": {
    "content": "### Query\n\nversion: ${query_build_version}\n\nrevision: ${query_build_revision}\n\nbuild date: ${query_build_date}"
   }
  },
  { "title": "Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Index Inserts Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (clusterName)(rate(jaeger_bulk_index_inserts_total{clusterName=~\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "Index Errors Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (clusterName)(rate(jaeger_bulk_index_errors_total{clusterName=~\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "Index Latency OK - 95 Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(jaeger_bulk_index_latency_ok_bucket{clusterName=~\"$cluster_name\"}[$__rate_interval])) by (le, clusterName))",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "Index Latency Error - 95 Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(jaeger_bulk_index_latency_err_bucket{clusterName=~\"$cluster_name\"}[$__rate_interval])) by (le, clusterName))",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  { "title": "Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Span Ingest Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (clusterName)(rate(jaeger_collector_spans_dropped_total{clusterName=~\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "{{clusterName}} error"
    },
    {
     "expr": "sum by(clusterName)(rate(jaeger_collector_spans_received_total{clusterName=~\"$cluster_name\"}[$__rate_interval])) - sum by(clusterName)(rate(jaeger_collector_spans_dropped_total{clusterName=~\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "{{clusterName}} success"
    }
   ]
  },
  {
   "title": "% Spans Dropped/Rejected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (clusterName)(rate(jaeger_collector_spans_dropped_total{clusterName=~\"$cluster_name\"}[$__rate_interval])) / sum by (clusterName)(rate(jaeger_collector_spans_received_total{clusterName=~\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "{{clusterName}} dropped"
    },
    {
     "expr": "sum by (clusterName)(rate(jaeger_collector_spans_rejected_total{clusterName=~\"$cluster_name\"}[$__rate_interval])) / sum by (clusterName)(rate(jaeger_collector_spans_received_total{clusterName=~\"$cluster_name\"}[$__rate_interval]))",
     "legendFormat": "{{clusterName}} rejected"
    }
   ]
  },
  {
   "title": "Span Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (clusterName)(jaeger_collector_queue_length{clusterName=~\"$cluster_name\"})",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "Span Queue Time - 95 Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(jaeger_collector_in_queue_latency_bucket{clusterName=~\"$cluster_name\"}[$__rate_interval])) by (le, clusterName))",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum by (clusterName)(rate(jaeger_query_requests_total{clusterName=~\"$cluster_name\", result=\"ok\"}[$__rate_interval]))",
     "legendFormat": "{{clusterName}} success"
    }
   ]
  },
  {
   "title": "Latency - 99 Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(jaeger_query_latency_bucket{clusterName=~\"$cluster_name\"}[$__rate_interval])) by (le, clusterName))",
     "legendFormat": "{{clusterName}}"
    }
   ]
  }
 ]
}