{
 "title": "Logging Health",
 "description": "This is a simple dashboard for banzaicloud/logging-operator and OpenSearch operator",
 "tags": [ "logging" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "Cluster name", "query": { "query": "label_values(clusterName)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{clusterName=\"$cluster_name\",job=\"node-exporter\", sysname!=\"Darwin\"}, instance)"
    }
   },
   {
    "name": "opensearch",
    "query": {
     "query": "label_values(opensearch_cluster_status{}, cluster)"
    }
   },
   {
    "name": "fluentdplugin",
    "label": "Fluentd Plugin",
    "query": {
     "query": "label_values(fluentd_output_status_emit_records, plugin_id)"
    }
   },
   {
    "name": "fluentbit",
    "query": {
     "query": "label_values(fluentbit_input_bytes_total,pod)"
    }
   },
   {
    "name": "fluentd",
    "query": {
     "query": "label_values(fluentd_output_status_emit_count,pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Opensearch Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logging Cluster Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_status{cluster=~\"$opensearch\"}) / count(opensearch_cluster_nodes_number{cluster=~\"$opensearch\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_nodes_number{cluster=~\"$opensearch\"}) / count(opensearch_cluster_nodes_number{cluster=~\"$opensearch\"})"
    }
   ]
  },
  {
   "title": "Active Data Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_datanodes_number{cluster=~\"$opensearch\"}) / count(opensearch_cluster_datanodes_number{cluster=~\"$opensearch\"})"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_pending_tasks_number{cluster=~\"$opensearch\"}) / count(opensearch_cluster_pending_tasks_number{cluster=~\"$opensearch\"})"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_shards_number{cluster=~\"$opensearch\",type=\"unassigned\"}) / count(opensearch_cluster_shards_number{cluster=~\"$opensearch\",type=\"unassigned\"})"
    }
   ]
  },
  {
   "title": "Active Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_shards_number{cluster=~\"$opensearch\",type=\"active\"}) / count(opensearch_cluster_shards_number{cluster=~\"$opensearch\",type=\"active\"})"
    }
   ]
  },
  {
   "title": "Active Primary Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_shards_number{cluster=~\"$opensearch\",type=\"active_primary\"}) / count(opensearch_cluster_shards_number{cluster=~\"$opensearch\",type=\"active_primary\"})"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_shards_number{cluster=~\"$opensearch\",type=\"initializing\"}) / count(opensearch_cluster_shards_number{cluster=~\"$opensearch\",type=\"initializing\"})"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_shards_number{cluster=~\"$opensearch\",type=\"relocating\"}) / count(opensearch_cluster_shards_number{cluster=~\"$opensearch\",type=\"relocating\"})"
    }
   ]
  },
  {
   "title": "Fluent Aggregated Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fluent-bit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\".*fluentbit.*\",clusterName=\"$cluster_name\"})",
     "legendFormat": "Active Fluent-bit"
    }
   ]
  },
  {
   "title": "Fluentd",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\".*fluentd.*\",pod!~\".*config.*\",clusterName=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Fluentbit Input Record",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{clusterName=\"$cluster_name\"}[2m]))"
    }
   ]
  },
  {
   "title": "Fluentbit Output Records",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{clusterName=\"$cluster_name\"}[2m]))"
    }
   ]
  },
  {
   "title": "Fluentd Router records/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_router_records_total[1m]))"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{clusterName=\"$cluster_name\",instance=\"$instance\", mode=\"idle\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU Requests Commitment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (clusterName)(kube_pod_container_resource_requests{clusterName=~\"$cluster_name\", resource=\"cpu\"}) / sum by (clusterName)(kube_node_status_allocatable{clusterName=~\"$cluster_name\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "CPU Limits Commitment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (clusterName)(kube_pod_container_resource_limits{clusterName=~\"$cluster_name\", resource=\"cpu\"}) / sum by (clusterName)(kube_node_status_allocatable{clusterName=~\"$cluster_name\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Ready Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\",clusterName=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Bad Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition!=\"Ready\",status=\"true\",clusterName=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Fluentbit Input Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total{clusterName=\"$cluster_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Fluentbit Output Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total{clusterName=\"$cluster_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Fluentd Output Emit Records",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_emit_records{clusterName=\"$cluster_name\",plugin_id=~\"^(flow|clusterflow):.*:.*:(output|clusteroutput).*:.*$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum by (clusterName)(node_memory_MemAvailable_bytes{clusterName=~\"$cluster_name\"}) / sum by (clusterName)(kube_node_status_allocatable{clusterName=~\"$cluster_name\", resource=\"memory\"}))"
    }
   ]
  },
  {
   "title": "Memory Requests Commitment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (clusterName)(kube_pod_container_resource_requests{clusterName=\"$cluster_name\", resource=\"memory\"}) / sum by (clusterName)(node_memory_VmallocTotal_bytes{clusterName=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "Memory Limits Commitment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (clusterName)(kube_pod_container_resource_limits{clusterName=\"$cluster_name\", resource=\"memory\"}) / sum by (clusterName)(node_memory_VmallocTotal_bytes{clusterName=\"$cluster_name\"})"
    }
   ]
  },
  {
   "title": "fluentd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fluentd Records by Plugin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(fluentd_output_status_emit_count{clusterName=\"$cluster_name\", pod=~\"$fluentd\",plugin_id=~\"$fluentdplugin\"}[5m])",
     "legendFormat": "{{ plugin_id }}/{{pod}}"
    }
   ]
  },
  {
   "title": "Fluentd Buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (clusterName)(fluentd_status_buffer_total_bytes{clusterName=~\"$cluster_name\"})",
     "legendFormat": "{{clusterName}}"
    }
   ]
  },
  {
   "title": "Top Aggregated Fluentd Routes",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "topk(5, sum(rate(fluentd_router_records_total[1m])) by (flow, id))"
    }
   ]
  },
  {
   "title": "Fluentd Output Buffer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_total_bytes{clusterName=\"$cluster_name\",pod=~\"$fluentd\",plugin_id=~\"$fluentdplugin\"}",
     "legendFormat": "{{ plugin_id }} total bytes"
    },
    {
     "expr": "fluentd_output_status_buffer_queue_length{clusterName=\"$cluster_name\",pod=~\"$fluentd\",plugin_id=~\"$fluentdplugin\"}",
     "legendFormat": "{{plugin_id}} queue length"
    }
   ]
  },
  {
   "title": "Fluentd Buffer Disk",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{pod=~\"$fluentd\",mountpoint=\"/buffers\",endpoint=\"buffer-metrics\", fstype!=\"\"} - node_filesystem_free_bytes{pod=~\"$fluentd\",mountpoint=\"/buffers\",endpoint=\"buffer-metrics\", fstype!=\"\"}",
     "legendFormat": "Used: {{pod}}"
    },
    {
     "expr": "node_filesystem_size_bytes{pod=~\"$fluentd\",mountpoint=\"/buffers\",endpoint=\"buffer-metrics\", fstype!=\"\"}",
     "legendFormat": "Total: {{pod}}"
    }
   ]
  },
  {
   "title": "Fluentd Output Error and Retry",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_retry_count{clusterName=\"$cluster_name\",pod=~\"$fluentd\",plugin_id=~\"$fluentdplugin\"}[1m])) by (pod)",
     "legendFormat": "Retry {{pod}}"
    },
    {
     "expr": "sum(rate(fluentd_output_status_num_errors{clusterName=\"$cluster_name\",pod=~\"$fluentd\",plugin_id=~\"$fluentdplugin\"}[1m])) by (pod)",
     "legendFormat": "Error {{pod}}"
    }
   ]
  },
  {
   "title": "fluentbit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fluentbit Input Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total{clusterName=\"$cluster_name\",pod=~\"$fluentbit\"}[5m])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total{clusterName=\"$cluster_name\",pod=~\"$fluentbit\"}[5m])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluentbit Input Record",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{clusterName=\"$cluster_name\",pod=~\"$fluentbit\"}[5m])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Records",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{clusterName=\"$cluster_name\",pod=~\"$fluentbit\"}[5m])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Retries/Fails",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_total{clusterName=\"$cluster_name\",pod=~\"$fluentbit\"}[1m])) by (pod, name)",
     "legendFormat": "Retries {{ pod }}/{{name}}"
    },
    {
     "expr": "sum(rate(fluentbit_output_retries_failed_total{clusterName=\"$cluster_name\",pod=~\"$fluentbit\"}[1m])) by (pod, name)",
     "legendFormat": "Failed {{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_errors_total{clusterName=\"$cluster_name\",pod=~\"$fluentbit\"}[1m])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{ name }}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Dropped Records",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_dropped_records_total{clusterName=\"$cluster_name\",pod=~\"$fluentbit\"}[5m])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  },
  {
   "title": "Fluentbit Output Retried Records",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retried_records_total{clusterName=\"$cluster_name\",pod=~\"$fluentbit\"}[5m])) by (pod, name)",
     "legendFormat": "{{ pod }}/{{name}}"
    }
   ]
  }
 ]
}