{
 "title": "OpenTelemetry",
 "description": "otelcol metrics dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_version",
    "label": "service_version",
    "query": {
     "query": "query_result(sum(otelcol_process_uptime{}) by (service_version))\n"
    }
   },
   { "name": "cluster_name", "label": "Cluster", "query": { "query": "label_values(clusterName)" } },
   {
    "name": "service_name",
    "label": "service_version",
    "query": {
     "query": "query_result(sum(otelcol_process_uptime{}) by (service_name))\n"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "## Collector Service Info\n\nversion: ${service_version}\n\nname: ${service_name}\n\n"
   }
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Instance",
   "type": "stat",
   "description": "Otel Collector Instance",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(service_instance_id) (otelcol_process_cpu_seconds{clusterName=~\"$cluster_name\", service_instance_id=~\".*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "otelcol_process_cpu_seconds",
   "gridPos": { "h": 5, "w": 11, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(otelcol_process_cpu_seconds{clusterName=~\"$cluster_name\"}[$__rate_interval])*100) by (clusterName)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Memory Rss\navg(otelcol_process_memory_rss{}) by (instance)",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(otelcol_process_memory_rss{clusterName=~\"$cluster_name\"}) by (clusterName)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Trace Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "nodeGraph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "label_join(label_join(\n(rate(otelcol_receiver_accepted_spans{}[$__interval]))\n, \"id\", \"\", \"transport\", \"receiver\")\n, \"title\", \"\", \"transport\", \"receiver\")\n\nor\n\nlabel_replace(label_replace(\nsum by(service_name) (rate(otelcol_receiver_accepted_spans{}[$__interval]))\n, \"id\", \"processor\", \"dummynode\", \"\")\n, \"title\", \"processor\", \"dummynode\", \"\")\n\nor\nlabel_replace(label_replace(\n(rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n, \"id\", \"$0\", \"processor\", \".*\")\n, \"title\", \"$0\", \"processor\", \".*\")\n\nor\nlabel_replace(label_replace(\nsum by(exporter) (rate(otelcol_exporter_sent_spans{}[$__interval]))\n, \"id\", \"exporter\", \"dummynode\", \"\")\n, \"title\", \"exporter\", \"dummynode\", \"\")\n        \nor\nlabel_replace(label_replace(\nsum by(exporter) (rate(otelcol_exporter_sent_spans{}[$__interval]))\n, \"id\", \"$0\", \"exporter\", \".*\")\n, \"title\", \"$0\", \"exporter\", \".*\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\nlabel_replace(label_join(\n(rate(otelcol_receiver_accepted_spans{}[$__interval]))\n\n ,\"source\",\"\",\"transport\",\"receiver\")\n,\"target\",\"processor\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\n  or\n\n  label_join(\nlabel_replace(label_replace(\n  (rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n ,\"source\",\"processor\",\"\",\"\")\n,\"target\",\"$0\",\"processor\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")\n\nor\n  label_join(\nlabel_replace(label_replace(\n    (rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n ,\"source\",\"$0\",\"processor\",\".*\")\n,\"target\",\"exporter\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\nor\n  label_join(\nlabel_replace(label_replace(\n   (rate(otelcol_exporter_sent_spans{}[$__interval]))\n ,\"source\",\"exporter\",\"\",\"\")\n,\"target\",\"$0\",\"exporter\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted",
   "type": "stat",
   "description": "Spans Accepted by Receiver and Transport",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{clusterName=~\"$cluster_name\"}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "description": "Total Spans Accepted ",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{}[$__rate_interval])) ",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Batch",
   "type": "stat",
   "description": "Total Batch Processed",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_batch_batch_send_size_sum{}[$__rate_interval]))  by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{}[$__interval])) ",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "stat",
   "description": "Sent by Exporter",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{}[$__rate_interval])) by (exporter)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Refused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "description": "Total Spans Accepted ",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{}[$__rate_interval])) ",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "description": "otelcol_exporter_send_failed_spans",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{}[$__rate_interval])) ",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "description": "Sent by Exporter\notelcol_exporter_send_failed_spans",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{}[$__rate_interval])) by (exporter)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  { "title": "Metrics Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "type": "nodeGraph",
   "description": "Metrics Signalling Pipelines",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "\nlabel_join(label_join(\n(rate(otelcol_receiver_accepted_metric_points{}[$__interval]))\n, \"id\", \"\", \"transport\", \"receiver\")\n, \"title\", \"\", \"transport\", \"receiver\")\n\nor\n\nlabel_replace(label_replace(\nsum by(service_name) (rate(otelcol_receiver_accepted_spans{}[$__interval]))\n, \"id\", \"processor\", \"dummynode\", \"\")\n, \"title\", \"processor\", \"dummynode\", \"\")\n\n\n\nor\nlabel_replace(label_replace(\n(rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n, \"id\", \"$0\", \"processor\", \".*\")\n, \"title\", \"$0\", \"processor\", \".*\")\n\n\n\n\n\nor\nlabel_replace(label_replace(\nsum (rate(otelcol_exporter_sent_metric_points{}[$__interval]))\n, \"id\", \"exporter\", \"dummynode\", \"\")\n, \"title\", \"exporter\", \"dummynode\", \"\")\n\nor\nlabel_replace(label_replace(\nsum by(exporter) (rate(otelcol_exporter_sent_metric_points{}[$__interval]))\n, \"id\", \"$0\", \"exporter\", \".*\")\n, \"title\", \"$0\", \"exporter\", \".*\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\nlabel_replace(label_join(\n(rate(otelcol_receiver_accepted_metric_points{}[$__interval]))\n\n,\"source\",\"\",\"transport\",\"receiver\")\n,\"target\",\"processor\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\n\nor\n\nlabel_join(\nlabel_replace(label_replace(\n(rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n,\"source\",\"processor\",\"\",\"\")\n,\"target\",\"$0\",\"processor\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")\n\n\n\n\n\nor\n\n\nlabel_join(\nlabel_replace(label_replace(\n(rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n,\"source\",\"$0\",\"processor\",\".*\")\n,\"target\",\"exporter\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\nor\nlabel_join(\nlabel_replace(label_replace(\n(rate(otelcol_exporter_sent_metric_points{}[$__interval]))\n,\"source\",\"exporter\",\"\",\"\")\n,\"target\",\"$0\",\"exporter\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted",
   "type": "stat",
   "description": "otelcol_receiver_accepted_metric_points",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points{}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "description": "otelcol_receiver_accepted_metric_points\nTotal Accepted ",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points{}[$__rate_interval])) ",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Batch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_batch_batch_send_size_sum{}[$__rate_interval]))  by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "description": "Total Export ",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points{}[$__rate_interval])) ",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "stat",
   "description": "Sent by Exporter",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points{}[$__rate_interval])) by (exporter) ",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Refused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_metric_points{}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "description": "Total Refused \nsum(rate(otelcol_receiver_refused_metric_points{}[$__rate_interval])) ",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_metric_points{}[$__rate_interval])) ",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "gauge",
   "description": "Total Failed Export ",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_metric_points{}[$__rate_interval])) ",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "description": "Sent by Exporter\notelcol_exporter_send_failed_spans",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_metric_points{}[$__rate_interval])) by (exporter)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  { "title": "Prometheus Scrape", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Samples Scraped",
   "type": "piechart",
   "description": "sum_over_time(scrape_samples_scraped[$__range])/ count_over_time(scrape_samples_scraped[$__range])",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job, clusterName)((sum_over_time(scrape_samples_scraped{clusterName=~\"$cluster_name\"}[$__range]) / count_over_time(scrape_samples_scraped{clusterName=~\"$cluster_name\"}[$__range])/(5*30)))",
     "legendFormat": "{{job}} - {{clusterName}}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "gauge",
   "description": "scrape_samples_scraped{job!=\"\"}\nTotal Samples Scraped",
   "gridPos": { "h": 12, "w": 3, "x": 8, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(scrape_samples_scraped{clusterName=~\"$cluster_name\"}[$__range]) / count_over_time(scrape_samples_scraped{clusterName=~\"$cluster_name\"}[$__range])/(5*30)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "nodeGraph",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 51 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(\nsum (scrape_samples_scraped{clusterName=~\"$cluster_name\",job!=\"\"}) by (clusterName)\n, \"id\", \"$0\", \"clusterName\", \".*\")\n, \"title\", \"$0\", \"clusterName\", \".*\")\n,\"mainstat\",\"\",\"\",\"\")\n\nor \n\nlabel_replace(label_replace(label_replace(\nsum (scrape_samples_scraped{clusterName=~\"$cluster_name\",job!=\"\"})\n, \"id\", \"prometheus\", \"\", \"\")\n, \"title\", \"prometheus\", \"\", \"\")\n,\"mainstat\",\"\",\"\",\"\")\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\nlabel_replace(label_replace(\nsum (scrape_samples_scraped{clusterName=~\"$cluster_name\",job!=\"\"}) by (clusterName)\n,\"source\",\"$0\",\"clusterName\",\".*\")\n,\"target\",\"prometheus\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}