{
 "title": "Thanos",
 "tags": [ "monitoring" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "Cluster", "query": { "query": "label_values(clusterName)" } },
   {
    "name": "sidecar_namespace",
    "label": "Sidecar namespace",
    "query": {
     "query": "label_values(kube_pod_container_info{clusterName=~\"$cluster_name\", container=~\"thanos-sidecar.*\"}, namespace)"
    }
   },
   {
    "name": "sidecar_pod",
    "label": "Sidecar pod",
    "query": {
     "query": "label_values(kube_pod_container_info{clusterName=~\"$cluster_name\", container=~\"thanos-sidecar.*\"}, pod)"
    }
   },
   {
    "name": "thanos_namespace",
    "label": "Thanos namespace",
    "query": {
     "query": "label_values(thanos_build_info{clusterName=~\"$cluster_name\"}, namespace)"
    }
   },
   {
    "name": "thanos_job",
    "label": "Thanos job",
    "query": {
     "query": "label_values(thanos_build_info{clusterName=~\"$cluster_name\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (component)(thanos_status{clusterName=~\"$cluster_name\"})",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Rate (code 2xx)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (job, code) (rate(http_requests_total{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", job=~\"$thanos_job\", code=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Rate (code 3xx)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "sum by (job, code) (rate(http_requests_total{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", job=~\"$thanos_job\", code=~\"3..\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Rate (code 4xx)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum by (job, code) (rate(http_requests_total{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", job=~\"$thanos_job\", code=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Rate (code 5xx)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "expr": "sum by (job, code) (rate(http_requests_total{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", job=~\"$thanos_job\", code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GRPC Client Sent Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (job, code) (rate(grpc_client_msg_sent_total{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", job=~\"$thanos_job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GRPC Client Received Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum by (job, code) (rate(grpc_client_msg_received_total{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", job=~\"$thanos_job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GRPC Server Sent Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (job, code) (rate(grpc_server_msg_sent_total{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", job=~\"$thanos_job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GRPC Server Received Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "sum by (job, code) (rate(grpc_server_msg_received_total{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", job=~\"$thanos_job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Prometheus sidecar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "gRPC (Unary) Rate",
   "type": "timeseries",
   "description": "Shows rate of handled Unary gRPC requests from queriers.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (grpc_method, grpc_code) (rate(grpc_server_handled_total{clusterName=~\"$cluster_name\", namespace=~\"$sidecar_namespace\", pod=~\"$sidecar_pod\", grpc_type=\"unary\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "gRPC (Unary) Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(grpc_server_handled_total{clusterName=~\"$cluster_name\", grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\", container=\"thanos-sidecar.*\", grpc_type=\"unary\"}[$__rate_interval])) / sum by (job) (rate(grpc_server_handled_total{clusterName=~\"$cluster_name\", container=~\"thanos-sidecar.*\", grpc_type=\"unary\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 99th Percentile",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle requests.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(grpc_server_handling_seconds_bucket{clusterName=~\"$cluster_name\", container=~\"thanos-sidecar.*\", grpc_type=\"unary\"}[$__rate_interval])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Querier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (job, handler) (rate(http_requests_total{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", job=~\"$thanos_job\", handler=\"query_range\", code=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "{{job}} 2xx"
    },
    {
     "expr": "sum by (job, handler) (rate(http_requests_total{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", job=~\"$thanos_job\", handler=\"query_range\", code=~\"3..\"}[$__rate_interval]))",
     "legendFormat": "{{job}} 3xx"
    },
    {
     "expr": "sum by (job, handler) (rate(http_requests_total{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", job=~\"$thanos_job\", handler=\"query_range\", code=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "{{job}} 4xx"
    },
    {
     "expr": "sum by (job, handler) (rate(http_requests_total{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", job=~\"$thanos_job\", handler=\"query_range\", code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "{{job}} 5xx"
    }
   ]
  },
  {
   "title": "Latency 99th Percentile",
   "type": "timeseries",
   "description": "Shows how long has it taken to handle requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(http_request_duration_seconds_bucket{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", job=~\"$thanos_job\", handler=\"query_range\"}[$__rate_interval])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Store gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "gRPC (Unary) Rate",
   "type": "timeseries",
   "description": "Shows rate of handled Unary gRPC requests from queriers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (grpc_method, grpc_code) (rate(grpc_server_handled_total{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", job=~\"thanos-.*storegateway\", grpc_type=\"unary\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "gRPC (Unary) Errors",
   "type": "timeseries",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(grpc_server_handled_total{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",job=~\"thanos-.*storegateway.*\", grpc_type=\"unary\"}[$__rate_interval])) / sum by (job) (rate(grpc_server_handled_total{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", job=~\"thanos-.*storegateway.*\", grpc_type=\"unary\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Compactor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Compaction Rate",
   "type": "timeseries",
   "description": "Shows rate of execution for compactions against blocks that are stored in the bucket by compaction group.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_compact_group_compactions_total{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", job=~\"$thanos_job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Compaction Errors",
   "type": "timeseries",
   "description": "Shows rate of execution for compactions against blocks that are stored in the bucket by compaction group.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_compact_group_compactions_failures_total{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", job=~\"$thanos_job\"}[$__rate_interval])) / sum by (job) (rate(thanos_compact_group_compactions_total{clusterName=~\"$cluster_name\", namespace=~\"$thanos_namespace\", job=~\"$thanos_job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}