apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-tracing
spec:
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://logging-cluster.opensearch-system.svc:9200 # internal url for opensearch logging cluster
    esRollover:
      conditions: "{\"max_age\": \"1d\"}"
      readTTL: "168h"
      schedule: "55 23 * * *"
    esIndexCleaner:
      enabled: true
      schedule: "55 23 * * *"
      successfulJobsHistoryLimit: 7
      failedJobsHistoryLimit: 7
      numberOfDays: 7
  query:
    options:
      log-level: debug
      prometheus:
        server-url: https://rancher-monitoring-prometheus.cattle-monitoring-system.svc:9090 # internal url for prometheus (rancher-monitoring) instance
        query:
          support-spanmetrics-connector: true
      es.use-aliases: false
    metricsStorage:
      type: prometheus
  ingress:
    enabled: false
    annotations: {}
    hosts: {}
#    tls:
#      - hosts: {}
#        secretName: {}